namespace Assets.Scripts.Types
{
    public enum Body25
    {
        Nose,
        Neck,
        RShoulder,
        RElbow,
        RWrist,
        LShoulder,
        LElbow,
        LWrist,
        MidHip,
        RHip,
        RKnee,
        RAnkle,
        LHip,
        LKnee,
        LAnkle,
        REye,
        LEye,
        REar,
        LEar,
        LBigToe,
        LSmallToe,
        LHeel,
        RBigToe,
        RSmallToe,
        RHeel,
        Background
    }
}
